version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  db:
    image: postgres:15-alpine 
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: