version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      # - redis
    volumes:
      # Mount the entire backend directory for live development
      - ./backend:/backend
    networks:
      - shortener-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network

  # redis:
  #   image: redis:7-alpine 
  #   networks:
  #     - shortener-network

networks:
  shortener-network:
    driver: bridge

volumes:
  postgres_data: