"""Initial migration

Revision ID: f54e5f9565b6
Revises: 
Create Date: 2025-09-05 05:04:44.762889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54e5f9565b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappings',
    sa.Column('original_url', sa.String(length=2048), nullable=True),
    sa.Column('short_url', sa.String(length=10), nullable=True),
    sa.Column('url_type', sa.Enum('RANDOM', 'CUSTOM', name='urltype'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_mappings_original_url'), 'url_mappings', ['original_url'], unique=False)
    op.create_index(op.f('ix_url_mappings_short_url'), 'url_mappings', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_mappings_short_url'), table_name='url_mappings')
    op.drop_index(op.f('ix_url_mappings_original_url'), table_name='url_mappings')
    op.drop_table('url_mappings')
    # ### end Alembic commands ###
